#!/usr/local/bin/python3
import os
import sys
import argparse

# create parser for parsing input file name
parser = argparse.ArgumentParser(description='Create Orca slurm runscript')
parser.add_argument("-i", "--input", help="Input file name", required=True, type=str)
parser.add_argument("-c", "--cores", help="Number of cores", required=True, type=int)
args = parser.parse_args()


if args.cores > 32 and args.nodes < 2:
    print("Number of cores must be between 2 and 32")
    sys.exit()
elif args.cores == 1:
    queue = "#"
elif args.cores > 1 and args.cores <= 32:
    queue = "#$ -pe smp.pe"

# check if number of cores is the same as in input file
def check_cores(input_file, cores):
    with open(input_file, "r") as f:
        lines = f.readlines()
        for line in lines:
            if "nprocs" in line and not line.startswith("#"):
                if int(line.split()[2]) != cores:
                    print("Number of cores in input file does not match number of cores specified")
                    # ask user if they want to change number of cores in input file
                    change_cores = input("Do you want to change the number of cores in the input file? (Y/n)")
                    if change_cores == "y" or change_cores == "\n":
                        with open(input_file, "w") as f:
                            for line in lines:
                                if "nproc" in line:
                                    line = f"%pal   nprocs {cores}\n"
                                f.write(line)
                    else:
                        sys.exit()

# create slurm runscript
def create_runscript(queue, cores, input_file):
    script = f"""#!/bin/bash --login
#$ -cwd
{queue} {cores}          # Number of cores (2--32). Must match in your ORCA input file!
#$ -N {input_file.split(".")[0]}      # Job name""" + """
module purge
module load apps/binapps/orca/5.0.4

##########################
job=${JOB_NAME}

job=$(echo ${job%%.*})
##########################
export scratchlocation=/scratch

if [ ! -d $scratchlocation/$USER ]

then

  mkdir -p $scratchlocation/$USER

fi
##########################
tdir=$(mktemp -d $scratchlocation/$USER/orcajob_$JOB_ID-XXXX)

# Copy only the necessary stuff in submit directory to scratch directory. Add more here if needed.

cp  $SGE_O_WORKDIR/*.inp $tdir/

cp  $SGE_O_WORKDIR/*.gbw $tdir/

cp  $SGE_O_WORKDIR/*.xyz $tdir/
#########################

# Creating nodefile in scratch

# echo $HOSTNAME > $tdir/$job.nodes

# cd to scratch

cd $tdir

# Copy job and node info to beginning of outputfile

echo "Job execution start: $(date)" >>  $SGE_O_WORKDIR/$job.out

echo "Shared library path: $LD_LIBRARY_PATH" >>  $SGE_O_WORKDIR/$job.out

echo "Slurm Job ID is: ${JOB_ID}" >>  $SGE_O_WORKDIR/$job.out

echo "Slurm Job name is: ${JOB_NAME}" >>  $SGE_O_WORKDIR/$job.out

echo $HOSTNAME >> $SGE_O_WORKDIR/$job.out

#Start ORCA job. ORCA is started using full pathname (necessary for parallel execution). Output file is written directly to submit directory on frontnode.

$(which orca) $job.inp >  $SGE_O_WORKDIR/$job.out

# ORCA has finished here. Now copy important stuff back (xyz files, GBW files etc.). Add more here if needed.

cp $tdir/*.gbw $SGE_O_WORKDIR

cp $tdir/*.engrad $SGE_O_WORKDIR

cp $tdir/*.xyz $SGE_O_WORKDIR

cp $tdir/*.loc $SGE_O_WORKDIR

cp $tdir/*.qro $SGE_O_WORKDIR

cp $tdir/*.uno $SGE_O_WORKDIR

cp $tdir/*.unso $SGE_O_WORKDIR

cp $tdir/*.uco $SGE_O_WORKDIR

cp $tdir/*.hess $SGE_O_WORKDIR

cp $tdir/*.cis $SGE_O_WORKDIR

cp $tdir/*.dat $SGE_O_WORKDIR

cp $tdir/*.mp2nat $SGE_O_WORKDIR

cp $tdir/*.nat $SGE_O_WORKDIR

cp $tdir/*.scfp_fod $SGE_O_WORKDIR

cp $tdir/*.scfp $SGE_O_WORKDIR

cp $tdir/*.scfr $SGE_O_WORKDIR

cp $tdir/*.nbo $SGE_O_WORKDIR

cp $tdir/FILE.47 $SGE_O_WORKDIR

cp $tdir/*_property.txt $SGE_O_WORKDIR

cp $tdir/*spin* $SGE_O_WORKDIR
"""
    return script

# check if input file exists
if not os.path.isfile(args.input):
    print("Input file does not exist")
    sys.exit()
# if input file exists, create slurm runscript and adjust number of cores
else:
    # check if number of cores in input file matches number of cores specified
    check_cores(args.input, args.cores)
    with open("run.sh", "w") as f:
        f.write(create_runscript(queue, args.cores, args.input))
    os.system(f"qsub run.sh {args.input}")
    
