#!/bin/bash

if [ -z $4 ]
then
	echo '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'
	echo '!!     ERROR: THERE MUST BE 4 ARGUMENTS     !!'
	echo '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'
	echo ''
	echo 'Usage: sub_g16 file time project queue'
	echo 'Available queues: DevQ, ProdQ, LongQ'
	exit
fi

name=$4

echo "working with $4"
echo "#!/bin/bash "                                                     >  ${name}_all.job
echo "# All the informations about queues can be obtained by 'sinfo'"   >> ${name}_all.job
echo "# PARTITION AVAIL  TIMELIMIT "                                    >> ${name}_all.job
echo "# DevQ         up    1:00:00                               "      >> ${name}_all.job
echo "# ProdQ*       up 3-00:00:00                               "      >> ${name}_all.job
echo "# LongQ        up 6-00:00:00                               "      >> ${name}_all.job
echo "# ShmemQ       up 3-00:00:00                               "      >> ${name}_all.job
echo "# PhiQ         up 1-00:00:00                               "      >> ${name}_all.job
echo "# GpuQ         up 2-00:00:00                               "      >> ${name}_all.job
echo "# Slurm flags                                              "      >> ${name}_all.job
echo "#SBATCH -p $3                                              "      >> ${name}_all.job
echo "#SBATCH -N 1                                               "      >> ${name}_all.job
echo "#SBATCH --job-name=$4                                      "      >> ${name}_all.job
echo "#SBATCH -t $1:00                                           "      >> ${name}_all.job
echo "# Charge job to myaccount                                  "      >> ${name}_all.job
echo "#SBATCH -A $2                                              "      >> ${name}_all.job
echo "# Write stdout+stderr to file                              "      >> ${name}_all.job
echo "#SBATCH -o $4.txt                                          "      >> ${name}_all.job
echo "# Mail me on job start & end                               "      >> ${name}_all.job
echo "#SBATCH --mail-user=innigo.iribarren@gmail.com             "      >> ${name}_all.job
echo "#SBATCH --mail-type=BEGIN,END                              "      >> ${name}_all.job
echo 'cd $SLURM_SUBMIT_DIR                                       '      >> ${name}_all.job
echo "module load   gaussian/16c01                               "      >> ${name}_all.job
echo "                                                           "      >> ${name}_all.job
echo "export GAUSS_SCRDIR=/scratch/global                        "      >> ${name}_all.job
echo "export BINDIR=/ichec/home/users/iiribarren/nbo7/bin        "      >> ${name}_all.job
echo "                                                           "      >> ${name}_all.job

for j in *$4*.com; do 
	head=$(echo $j | awk -F.com '{print $1}')
	file="$file    $head"
done

for j in $file; do 
	echo "g16 < $j.com > $j.log                    "      >> ${name}_all.job
done

#sbatch ${name}_all.job
